# Generated by Django 4.2.20 on 2025-03-21 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjusted_gross_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('haircut_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('daily_advance_fee', models.DecimalField(decimal_places=4, max_digits=5)),
                ('customer_name', models.CharField(max_length=255)),
                ('currency_code', models.CharField(max_length=3)),
                ('customer_id', models.IntegerField()),
                ('revenue_source_id', models.IntegerField()),
                ('revenue_source_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['customer_id', 'created_at'], name='invoices_in_custome_3fb014_idx')],
            },
        ),
    ]
