# Generated by Django 4.2.20 on 2025-03-21 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='advance_duration',
            field=models.IntegerField(default=30),
        ),
    ]
