# Generated by Django 4.2.7 on 2025-03-21 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_invoice_invoice_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-created_at']},
        ),
    ]
